'use strict';
function parseCSV(text){let rows=[],row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){let c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else if(!cell||quoted)quoted=!quoted;else throw Error('Unexpected quote in CSV.');}else if(!quoted&&(c===','||c==='\n'||c==='\r')){row.push(cell.trim());cell='';if(c!==','){if(row.some(Boolean))rows.push(row);row=[];if(c==='\r'&&text[i+1]==='\n')i++;}}else cell+=c;}if(quoted)throw Error('Unclosed CSV quote.');row.push(cell.trim());if(row.some(Boolean))rows.push(row);return rows;}
function parseData(text,mode){let csv=parseCSV(text.replace(/^\uFEFF/,''));if(csv.length<2)throw Error('Include a header and at least one score row.');let head=csv.shift().map(x=>x.toLowerCase()),required=['player','goalie','session','evaluator','score'],cols=required.map(x=>head.indexOf(x));if(cols.some(x=>x<0)||new Set(head).size!==head.length)throw Error('Use unique headers: player,goalie,session,evaluator,score.');let players=[],sessions=[],evaluators=[],seen=new Set(),rows=[];const index=(a,x)=>{if(!a.includes(x))a.push(x);return a.indexOf(x);};csv.forEach((r,i)=>{if(r.length!==head.length)throw Error('Row '+(i+2)+' has the wrong number of columns.');let [p,g,d,j,s]=cols.map(k=>r[k]);g=g.toUpperCase();if(g!=='Y'&&g!=='N')throw Error('Row '+(i+2)+': goalie must be Y or N.');if((mode==='goalies')!==(g==='Y'))return;if(!p||!d||!j||[p,d,j].some(x=>x.length>50))throw Error('Row '+(i+2)+': use nonempty IDs of at most 50 characters.');if(!/^[1-7]$/.test(s))throw Error('Row '+(i+2)+': score must be a single integer 1–7.');let key=JSON.stringify([p,d,j]);if(seen.has(key))throw Error('Duplicate rating for '+p+', '+d+', '+j+'.');seen.add(key);rows.push({p:index(players,p),d:index(sessions,d),j:index(evaluators,j),score:Number(s)});});if(players.length<2||players.length>100||sessions.length>12||evaluators.length>30||rows.length>12000)throw Error('Use 2–100 players, at most 12 sessions, 30 evaluators, and 12,000 ratings.');if(mode==='goalies'){if(players.length!==2)throw Error('Goalie analysis requires exactly two players.');for(let d=0;d<sessions.length;d++){let panel=p=>rows.filter(o=>o.d===d&&o.p===p).map(o=>o.j).sort((a,b)=>a-b).join(',');if(panel(0)!==panel(1))throw Error('Both goalies must have ratings from the same evaluators in each session.');}}return {players,sessions,evaluators,rows};}
function ranks(values){return values.map(v=>1+values.filter(x=>x>v+1e-10).length+(values.filter(x=>Math.abs(x-v)<=1e-10).length-1)/2);}
function scores(data,method,weights){return data.players.map((_,p)=>{let days=data.sessions.map((_,d)=>data.rows.filter(o=>o.p===p&&o.d===d).map(o=>o.score)).map((ratings,d)=>{let a=ratings.slice().sort((x,y)=>x-y);if(method==='trim'&&a.length>=3)a=a.slice(1,-1);return {d,n:ratings.length,sum:ratings.reduce((a,b)=>a+b,0),mean:a.length?a.reduce((a,b)=>a+b,0)/a.length:null};}).filter(d=>d.n);if(method==='sum')return days.reduce((a,d)=>a+d.sum,0);if(method==='rating-mean')return days.reduce((a,d)=>a+d.sum,0)/days.reduce((a,d)=>a+d.n,0);let denominator=days.reduce((a,d)=>a+(method==='weighted'?weights[d.d]:1),0);return denominator?days.reduce((a,d)=>a+d.mean*(method==='weighted'?weights[d.d]:1),0)/denominator:NaN;});}
function dayWinner(data){let wins=[0,0],ties=0,days=data.sessions.map((session,d)=>{let totals=[0,1].map(p=>data.rows.filter(o=>o.p===p&&o.d===d).reduce((a,o)=>a+o.score,0));if(totals[0]===totals[1])ties++;else wins[totals[1]>totals[0]?1:0]++;return {session,totals};});return {wins,ties,days,winner:wins[0]===wins[1]?'Tie':data.players[wins[1]>wins[0]?1:0]};}
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function download(name,content,type='text/csv'){let a=document.createElement('a'),url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
let data=null,posterior=null,worker=null,fittedText=null,fittedMode=null,fittedOpt=null;
function numeric(id,min,max,integer=false){let v=Number(document.getElementById(id).value);if(!Number.isFinite(v)||v<min||v>max||integer&&!Number.isInteger(v))throw Error('Check '+document.getElementById(id).parentElement.firstChild.textContent.trim()+'.');return v;}
function initialize(){const $=id=>document.getElementById(id),methodLabels={'session-mean':'Average of session averages','sum':'Raw sum of all ratings','rating-mean':'Average of all evaluator ratings','weighted':'Weighted average of session averages','trim':'Session averages after dropping highest and lowest','days':'Most evaluation days won','posterior':'Model-based median skill ranking'};
function setRules(){let g=$('mode').value==='goalies',rules=g?['days','session-mean','weighted','trim','sum','posterior']:['session-mean','rating-mean','weighted','trim','sum','posterior'];$('summary-rule').replaceChildren();rules.forEach(rule=>{let o=document.createElement('option');o.value=rule;o.textContent=methodLabels[rule];$('summary-rule').append(o);});}
function invalidate(){if(worker){worker.terminate();worker=null;}posterior=null;$('results').hidden=true;$('cancel').hidden=true;$('progress').hidden=true;$('run').disabled=false;}
function updateData(){try{data=parseData($('csv').value,$('mode').value);$('data-status').textContent=data.players.length+' players · '+data.sessions.length+' sessions · '+data.evaluators.length+' evaluators · '+data.rows.length+' ratings';$('data-status').className='';let oldWeights=new Map([...$('weights').querySelectorAll('input')].map(x=>[x.dataset.session,x.value]));$('weights').replaceChildren();data.sessions.forEach((s,d)=>{let label=document.createElement('label');label.textContent=s+' weight';let input=document.createElement('input');input.type='number';input.min='0';input.max='20';input.step='.25';input.value=oldWeights.has(s)?oldWeights.get(s):'1';input.dataset.day=d;input.dataset.session=s;input.addEventListener('input',updateRanking);label.append(input);$('weights').append(label);});updateRanking();}catch(e){data=null;$('data-status').textContent=e.message;$('data-status').className='error';$('ranking-results').hidden=true;}}
function updateRanking(){if(!data)return;try{$('ranking-status').className='';let weights=[...$('weights').querySelectorAll('input')].map(x=>{let v=Number(x.value);if(!Number.isFinite(v)||v<0||v>20)throw Error('Weights must be between 0 and 20.');return v;}),method=$('summary-rule').value,base=scores(data,'session-mean',weights),selected=method==='days'?dayWinner(data).wins:method==='posterior'?(posterior?posterior.summary.map(x=>x.skill[1]):null):scores(data,method,weights);if(!selected)throw Error('Run the uncertainty analysis before selecting model-based ranking.');if(selected.some(v=>!Number.isFinite(v)))throw Error('Every player needs at least one observed session with positive weight.');let br=ranks(base),sr=ranks(selected),order=data.players.map((_,p)=>p).sort((p,q)=>sr[p]-sr[q]||p-q);$('ranking-results').hidden=false;$('ranking-status').textContent='Compared with the unweighted average of session averages. Equal scores have tied ranks; no coin flip or ID-based winner is used.';
let counts=data.players.map((_,p)=>data.rows.filter(o=>o.p===p).length),notes=[];if(method==='sum'&&new Set(counts).size>1)notes.push('Raw sums reward additional ratings: players have different numbers of observations.');if(method==='weighted')notes.push('Weights apply to sessions a player attended; missing sessions receive no zero or penalty.');if(method==='trim')notes.push('Highest and lowest ratings are removed separately within each player/session. Sessions with fewer than three ratings retain all ratings. Removing extremes is a rule choice, not a model of uncertainty.');$('rule-note').textContent=notes.join(' ');
$('ranking-rows').innerHTML=order.map(p=>{let change=br[p]-sr[p],movement=change===0?'Unchanged':change>0?'↑ '+change.toFixed(1):'↓ '+(-change).toFixed(1);return '<tr><td>'+esc(data.players[p])+'</td><td>'+selected[p].toFixed(2)+'</td><td>'+br[p].toFixed(1)+'</td><td>'+sr[p].toFixed(1)+'</td><td>'+movement+'</td><td><div class="rank-track" aria-label="Original rank '+br[p]+', selected rank '+sr[p]+'"><span class="baseline-marker" style="left:'+((br[p]-1)/(data.players.length-1)*100)+'%"></span><span class="selected-marker" style="left:'+((sr[p]-1)/(data.players.length-1)*100)+'%"></span></div></td></tr>';}).join('');$('ranking-title').textContent=methodLabels[method];$('movement-summary').textContent=data.players.filter((_,p)=>br[p]!==sr[p]).length+' of '+data.players.length+' players change rank under this rule.';
if($('mode').value==='goalies'){let current=dayWinner(data),winner=selected[0]===selected[1]?'Tie':data.players[selected[1]>selected[0]?1:0];$('rule-note').textContent+=' Days-won method: '+current.winner+' ('+current.wins[0]+' vs '+current.wins[1]+' days won; '+current.ties+' tied days). Selected summary rule: '+winner+'.';}
if(posterior)renderPosterior();}catch(e){$('ranking-status').textContent=e.message;$('ranking-status').className='error';}}
function options(){let mode=$('mode').value,cut1=mode==='skaters'?numeric('cut1',1,data.players.length-1,true):1,cut2=mode==='skaters'?numeric('cut2',2,data.players.length-1,true):1;if(mode==='skaters'&&cut2<=cut1)throw Error('A + B1 boundary must be larger than the A boundary and smaller than the player pool.');return {early:numeric('early',.1,3),late:numeric('late',.1,3),error:numeric('error',.2,3),bias:numeric('bias',0,2),iterations:Number($('effort').value),cut1,cut2};}
function pair(){if(!posterior)return;let x=Number($('pair-x').value),y=Number($('pair-y').value);if(x===y){$('pair-results').textContent='Choose two different players.';return;}let diff=posterior.draws.map(d=>d[y]-d[x]),n=diff.length,values=[['Probability '+data.players[y]+' is more skilled',diff.filter(v=>v>0).length/n],['Probability difference is 0.5 or less',diff.filter(v=>Math.abs(v)<=.5).length/n],['Probability difference is 1 or less',diff.filter(v=>Math.abs(v)<=1).length/n]];$('pair-results').innerHTML=values.map(([label,p])=>'<div class="metric">'+esc(label)+'<strong>'+percent(p)+'</strong></div>').join('');}
const percent=p=>(100*p).toFixed(1)+'%';
function renderPosterior(){if(!posterior)return;let low=numeric('review-low',0,49)/100,high=numeric('review-high',51,100)/100,diag=posterior.diagnostics,bad=diag.maxRhat>1.01||diag.minESS<400;$('results').hidden=false;$('diagnostics').innerHTML='<div class="box'+(bad?' error':'')+'"><strong>'+(bad?'Sampling warning: use extended sampling before relying on these results.':'Sampling checks passed for this run.')+'</strong> '+diag.retainedDraws.toLocaleString()+' retained draws; maximum split R̂ '+diag.maxRhat.toFixed(3)+'; minimum approximate ESS '+Math.floor(diag.minESS)+'. These checks address numerical sampling, not model validity.</div>';$('skater-results').hidden=$('mode').value!=='skaters';
if($('mode').value==='goalies'){let win=dayWinner(data);$('decision').innerHTML='<p class="decision"><strong>Current days-won method selects: '+esc(win.winner)+'</strong><br>'+esc(data.players[0])+': '+win.wins[0]+' days won · '+esc(data.players[1])+': '+win.wins[1]+' days won · '+win.ties+' days tied</p>'; }else{$('decision').innerHTML='';let mean=scores(data,'session-mean',[]),order=data.players.map((_,p)=>p).sort((p,q)=>mean[q]-mean[p]||p-q),flagged=[];$('player-rows').innerHTML=order.map(p=>{let s=posterior.summary[p],flags=[];if(s.pA>=low&&s.pA<=high)flags.push('A / B1');if(s.pAB>=low&&s.pAB<=high)flags.push('B1 / B2');if(flags.length)flagged.push(data.players[p]);let rows=data.rows.filter(o=>o.p===p),sessions=new Set(rows.map(o=>o.d)).size;return '<tr class="'+(flags.length?'bubble':'')+'"><td>'+esc(data.players[p])+'</td><td>'+mean[p].toFixed(2)+'</td><td>'+sessions+' / '+rows.length+'</td><td>'+percent(s.pA)+'</td><td>'+percent(s.pAB)+'</td><td><div class="interval" aria-label="90 percent skill interval '+s.skill[0].toFixed(2)+' to '+s.skill[2].toFixed(2)+'"><span style="left:'+((s.skill[0]-1)/6*100)+'%;width:'+((s.skill[2]-s.skill[0])/6*100)+'%"></span><b style="left:'+((s.skill[1]-1)/6*100)+'%"></b></div>'+s.skill[0].toFixed(2)+'–'+s.skill[2].toFixed(2)+'</td><td class="flag">'+(flags.join('; ')||'Outside review range')+'</td></tr>';}).join('');$('bubble-summary').textContent=flagged.length+' of '+data.players.length+' players are flagged using '+Math.round(low*100)+'–'+Math.round(high*100)+'% probabilities. This is evidence for review, not a replacement team list.';}
pair();}
setRules();
$('csv').addEventListener('change',()=>{invalidate();updateData();});$('summary-rule').addEventListener('change',updateRanking);['review-low','review-high'].forEach(id=>$(id).addEventListener('change',()=>{try{renderPosterior();}catch(e){$('status').textContent=e.message;}}));
['early','late','error','bias','effort','cut1','cut2'].forEach(id=>$(id).addEventListener('change',()=>{invalidate();$('status').textContent='Settings changed. Run the uncertainty analysis again.';}));
$('mode').addEventListener('change',()=>{invalidate();setRules();let g=$('mode').value==='goalies';$('skater-settings').hidden=g;for(const [id,v] of Object.entries(g?{early:.5,late:1,error:.5,bias:0}:{early:.65,late:.9,error:1.25,bias:.35}))$(id).value=v;updateData();});
$('upload').addEventListener('change',async()=>{let file=$('upload').files[0];if(!file)return;if(file.size>2000000){$('data-status').textContent='Choose a CSV smaller than 2 MB.';return;}invalidate();$('csv').value=await file.text();updateData();});
$('template').onclick=()=>download('hockey-score-template.csv','player,goalie,session,evaluator,score\n');
$('example').onclick=()=>{invalidate();$('csv').value=$('mode').value==='goalies'?window.GOALIE_EXAMPLE:window.SKATER_EXAMPLE;updateData();};
$('run').onclick=()=>{try{invalidate();updateData();if(!data)throw Error('Correct the score input before running.');let opt=options();$('status').className='';fittedOpt=opt;fittedText=$('csv').value;fittedMode=$('mode').value;$('status').textContent='Sampling plausible skills and evaluator effects…';$('run').disabled=true;$('cancel').hidden=false;$('progress').hidden=false;$('progress').value=0;worker=new Worker('analysis-worker.js');worker.onerror=e=>{invalidate();$('status').textContent='Analysis could not run: '+e.message;};worker.onmessage=e=>{if(e.data.progress!==undefined){$('progress').value=e.data.progress;return;}if(e.data.error){invalidate();$('status').textContent=e.data.error;return;}posterior=e.data.result;worker.terminate();worker=null;$('progress').value=100;$('run').disabled=false;$('cancel').hidden=true;$('status').textContent='Analysis complete. Summary-rule changes update rankings immediately; model-setting changes require another run.';for(const id of ['pair-x','pair-y']){$(id).replaceChildren();data.players.forEach((p,i)=>{let o=document.createElement('option');o.textContent=p;o.value=i;$(id).append(o);});}$('pair-y').value='1';updateRanking();renderPosterior();};worker.postMessage({data,opt});}catch(e){$('status').textContent=e.message;$('status').className='error';}};
$('cancel').onclick=()=>{invalidate();$('status').textContent='Analysis stopped.';};['pair-x','pair-y'].forEach(id=>$(id).addEventListener('change',pair));
$('export').onclick=()=>{if(!posterior)return;let output={analysisMode:fittedMode,createdAt:new Date().toISOString(),model:'Ordinal probit with session performance and persistent evaluator effects',assumptions:fittedOpt,reviewRange:[Number($('review-low').value)/100,Number($('review-high').value)/100],diagnostics:posterior.diagnostics,players:data.players.map((id,p)=>({id,...posterior.summary[p]})),inputCSV:fittedText,posteriorSkillDraws:posterior.draws,notes:'Probabilities depend on model assumptions and concern fixed reference rank boundaries, not staged team assignment.'};download('hockey-uncertainty-results.json',JSON.stringify(output,null,2),'application/json');};
}
if(typeof document!=='undefined')document.addEventListener('DOMContentLoaded',initialize);
if(typeof module!=='undefined')module.exports={parseCSV,parseData,scores,ranks,dayWinner};
